apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-03-29T19:44:40Z"
  generation: 1
  labels:
    app: backend
  name: backend
  namespace: default
  resourceVersion: "169343"
  uid: 7cb2bd42-16e9-4cf9-9247-467432c2411c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: mehrshadlotfi/backend:v1
        imagePullPolicy: IfNotPresent
        name: backend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
