apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
    app.kubernetes.io/managed-by: Helm
  name: frontend
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontend
  type: NodePort
